database:
  host: 127.0.0.1
  port: 3306
  username: root
  password: password
  database: goidm
cache:
  type: "redis"
  address: "127.0.0.1:6379"
  username: ""
  password: ""
auth:
  hash:
    cost: 10
  token:
    expires_in: 24h
    regenerate_token_before_expiry: 1h
grpc:
  address: 127.0.0.1:8080
  get_download_task_file:
    response_buffer_size: 1kB
http:
  address: 127.0.0.1:8081
kafka:
  host: 127.0.0.1
  port: 9092
  client_id: "go_idm"
download:
  mode: s3
  bucket: downloaded-files
  address: "127.0.0.1:9000"
  username: "ROOTUSER"
  password: "CHANGEME123"